// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DisableRotation() {
  return window['go']['main']['App']['DisableRotation']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnableRotation(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EnableRotation'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ForceSwitch() {
  return window['go']['main']['App']['ForceSwitch']();
}

export function GetActiveProxy() {
  return window['go']['main']['App']['GetActiveProxy']();
}

export function GetConnectedDevices() {
  return window['go']['main']['App']['GetConnectedDevices']();
}

export function GetEngineStatus() {
  return window['go']['main']['App']['GetEngineStatus']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetProxies(arg1, arg2) {
  return window['go']['main']['App']['GetProxies'](arg1, arg2);
}

export function GetRotationPool() {
  return window['go']['main']['App']['GetRotationPool']();
}

export function GetRotationStatus() {
  return window['go']['main']['App']['GetRotationStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function KickDevice(arg1) {
  return window['go']['main']['App']['KickDevice'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2);
}
