// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {proxy} from '../models';
import {pb} from '../models';
import {metadata} from '../models';

export function Connect(arg1:string,arg2:number):Promise<void>;

export function DisableRotation():Promise<void>;

export function Disconnect():Promise<void>;

export function EnableRotation(arg1:number,arg2:Array<string>,arg3:string,arg4:number,arg5:number,arg6:boolean):Promise<void>;

export function ForceSwitch():Promise<void>;

export function GetActiveProxy():Promise<models.Proxy>;

export function GetConnectedDevices():Promise<Array<proxy.ConnectedDevice>>;

export function GetEngineStatus():Promise<pb.EngineStatus>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetProxies(arg1:number,arg2:string):Promise<Array<models.Proxy>>;

export function GetRotationPool():Promise<Array<models.Proxy>>;

export function GetRotationStatus():Promise<pb.RotationStatus>;

export function GetSettings():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<metadata.SystemInfo>;

export function KickDevice(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<void>;

export function UpdateSettings(arg1:any,arg2:any):Promise<void>;
