// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyEngine_Connect_FullMethodName             = "/engine.v1.ProxyEngine/Connect"
	ProxyEngine_Disconnect_FullMethodName          = "/engine.v1.ProxyEngine/Disconnect"
	ProxyEngine_GetActiveProxy_FullMethodName      = "/engine.v1.ProxyEngine/GetActiveProxy"
	ProxyEngine_StreamProxyUpdates_FullMethodName  = "/engine.v1.ProxyEngine/StreamProxyUpdates"
	ProxyEngine_GetRegions_FullMethodName          = "/engine.v1.ProxyEngine/GetRegions"
	ProxyEngine_GetEngineStatus_FullMethodName     = "/engine.v1.ProxyEngine/GetEngineStatus"
	ProxyEngine_GetPoolSummary_FullMethodName      = "/engine.v1.ProxyEngine/GetPoolSummary"
	ProxyEngine_GetProxies_FullMethodName          = "/engine.v1.ProxyEngine/GetProxies"
	ProxyEngine_ReportUsage_FullMethodName         = "/engine.v1.ProxyEngine/ReportUsage"
	ProxyEngine_GetBlockStats_FullMethodName       = "/engine.v1.ProxyEngine/GetBlockStats"
	ProxyEngine_ToggleAdBlock_FullMethodName       = "/engine.v1.ProxyEngine/ToggleAdBlock"
	ProxyEngine_CheckDomain_FullMethodName         = "/engine.v1.ProxyEngine/CheckDomain"
	ProxyEngine_Authenticate_FullMethodName        = "/engine.v1.ProxyEngine/Authenticate"
	ProxyEngine_RefreshToken_FullMethodName        = "/engine.v1.ProxyEngine/RefreshToken"
	ProxyEngine_GetConfig_FullMethodName           = "/engine.v1.ProxyEngine/GetConfig"
	ProxyEngine_UpdateConfig_FullMethodName        = "/engine.v1.ProxyEngine/UpdateConfig"
	ProxyEngine_GetAnalyticsSummary_FullMethodName = "/engine.v1.ProxyEngine/GetAnalyticsSummary"
	ProxyEngine_GetTopProxies_FullMethodName       = "/engine.v1.ProxyEngine/GetTopProxies"
)

// ProxyEngineClient is the client API for ProxyEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ═══════════════════════════════════════════════════════════
// ProxyEngine — gRPC service بين Engine.exe و Client.exe
// ═══════════════════════════════════════════════════════════
type ProxyEngineClient interface {
	// ── الاتصال والقطع ──
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// ── البروكسي النشط ──
	GetActiveProxy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProxyInfo, error)
	StreamProxyUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProxyUpdate], error)
	// ── المناطق ──
	GetRegions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RegionsResponse, error)
	// ── الحالة ──
	GetEngineStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStatus, error)
	GetPoolSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PoolSummary, error)
	GetProxies(ctx context.Context, in *GetProxiesRequest, opts ...grpc.CallOption) (*ProxiesResponse, error)
	// ── الاستهلاك ──
	ReportUsage(ctx context.Context, in *UsageReport, opts ...grpc.CallOption) (*UsageResponse, error)
	// ── AdBlock ──
	GetBlockStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BlockStats, error)
	ToggleAdBlock(ctx context.Context, in *ToggleRequest, opts ...grpc.CallOption) (*ToggleResponse, error)
	CheckDomain(ctx context.Context, in *DomainCheckRequest, opts ...grpc.CallOption) (*DomainCheckResponse, error)
	// ── المصادقة ──
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	RefreshToken(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// ── الإعدادات ──
	GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigResponse, error)
	UpdateConfig(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// ── التحليلات ──
	GetAnalyticsSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AnalyticsSummary, error)
	GetTopProxies(ctx context.Context, in *TopProxiesRequest, opts ...grpc.CallOption) (*TopProxiesResponse, error)
}

type proxyEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyEngineClient(cc grpc.ClientConnInterface) ProxyEngineClient {
	return &proxyEngineClient{cc}
}

func (c *proxyEngineClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetActiveProxy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProxyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyInfo)
	err := c.cc.Invoke(ctx, ProxyEngine_GetActiveProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) StreamProxyUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProxyUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProxyEngine_ServiceDesc.Streams[0], ProxyEngine_StreamProxyUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ProxyUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyEngine_StreamProxyUpdatesClient = grpc.ServerStreamingClient[ProxyUpdate]

func (c *proxyEngineClient) GetRegions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionsResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_GetRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetEngineStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EngineStatus)
	err := c.cc.Invoke(ctx, ProxyEngine_GetEngineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetPoolSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PoolSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolSummary)
	err := c.cc.Invoke(ctx, ProxyEngine_GetPoolSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetProxies(ctx context.Context, in *GetProxiesRequest, opts ...grpc.CallOption) (*ProxiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxiesResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_GetProxies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) ReportUsage(ctx context.Context, in *UsageReport, opts ...grpc.CallOption) (*UsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_ReportUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetBlockStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BlockStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockStats)
	err := c.cc.Invoke(ctx, ProxyEngine_GetBlockStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) ToggleAdBlock(ctx context.Context, in *ToggleRequest, opts ...grpc.CallOption) (*ToggleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_ToggleAdBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) CheckDomain(ctx context.Context, in *DomainCheckRequest, opts ...grpc.CallOption) (*DomainCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainCheckResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_CheckDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) RefreshToken(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) UpdateConfig(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetAnalyticsSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AnalyticsSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyticsSummary)
	err := c.cc.Invoke(ctx, ProxyEngine_GetAnalyticsSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyEngineClient) GetTopProxies(ctx context.Context, in *TopProxiesRequest, opts ...grpc.CallOption) (*TopProxiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopProxiesResponse)
	err := c.cc.Invoke(ctx, ProxyEngine_GetTopProxies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyEngineServer is the server API for ProxyEngine service.
// All implementations must embed UnimplementedProxyEngineServer
// for forward compatibility.
//
// ═══════════════════════════════════════════════════════════
// ProxyEngine — gRPC service بين Engine.exe و Client.exe
// ═══════════════════════════════════════════════════════════
type ProxyEngineServer interface {
	// ── الاتصال والقطع ──
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// ── البروكسي النشط ──
	GetActiveProxy(context.Context, *Empty) (*ProxyInfo, error)
	StreamProxyUpdates(*Empty, grpc.ServerStreamingServer[ProxyUpdate]) error
	// ── المناطق ──
	GetRegions(context.Context, *Empty) (*RegionsResponse, error)
	// ── الحالة ──
	GetEngineStatus(context.Context, *Empty) (*EngineStatus, error)
	GetPoolSummary(context.Context, *Empty) (*PoolSummary, error)
	GetProxies(context.Context, *GetProxiesRequest) (*ProxiesResponse, error)
	// ── الاستهلاك ──
	ReportUsage(context.Context, *UsageReport) (*UsageResponse, error)
	// ── AdBlock ──
	GetBlockStats(context.Context, *Empty) (*BlockStats, error)
	ToggleAdBlock(context.Context, *ToggleRequest) (*ToggleResponse, error)
	CheckDomain(context.Context, *DomainCheckRequest) (*DomainCheckResponse, error)
	// ── المصادقة ──
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	RefreshToken(context.Context, *RefreshRequest) (*AuthResponse, error)
	// ── الإعدادات ──
	GetConfig(context.Context, *Empty) (*ConfigResponse, error)
	UpdateConfig(context.Context, *ConfigUpdateRequest) (*ConfigResponse, error)
	// ── التحليلات ──
	GetAnalyticsSummary(context.Context, *Empty) (*AnalyticsSummary, error)
	GetTopProxies(context.Context, *TopProxiesRequest) (*TopProxiesResponse, error)
	mustEmbedUnimplementedProxyEngineServer()
}

// UnimplementedProxyEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyEngineServer struct{}

func (UnimplementedProxyEngineServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProxyEngineServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedProxyEngineServer) GetActiveProxy(context.Context, *Empty) (*ProxyInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveProxy not implemented")
}
func (UnimplementedProxyEngineServer) StreamProxyUpdates(*Empty, grpc.ServerStreamingServer[ProxyUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamProxyUpdates not implemented")
}
func (UnimplementedProxyEngineServer) GetRegions(context.Context, *Empty) (*RegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegions not implemented")
}
func (UnimplementedProxyEngineServer) GetEngineStatus(context.Context, *Empty) (*EngineStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEngineStatus not implemented")
}
func (UnimplementedProxyEngineServer) GetPoolSummary(context.Context, *Empty) (*PoolSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoolSummary not implemented")
}
func (UnimplementedProxyEngineServer) GetProxies(context.Context, *GetProxiesRequest) (*ProxiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxies not implemented")
}
func (UnimplementedProxyEngineServer) ReportUsage(context.Context, *UsageReport) (*UsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUsage not implemented")
}
func (UnimplementedProxyEngineServer) GetBlockStats(context.Context, *Empty) (*BlockStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockStats not implemented")
}
func (UnimplementedProxyEngineServer) ToggleAdBlock(context.Context, *ToggleRequest) (*ToggleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleAdBlock not implemented")
}
func (UnimplementedProxyEngineServer) CheckDomain(context.Context, *DomainCheckRequest) (*DomainCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDomain not implemented")
}
func (UnimplementedProxyEngineServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedProxyEngineServer) RefreshToken(context.Context, *RefreshRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedProxyEngineServer) GetConfig(context.Context, *Empty) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedProxyEngineServer) UpdateConfig(context.Context, *ConfigUpdateRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedProxyEngineServer) GetAnalyticsSummary(context.Context, *Empty) (*AnalyticsSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalyticsSummary not implemented")
}
func (UnimplementedProxyEngineServer) GetTopProxies(context.Context, *TopProxiesRequest) (*TopProxiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopProxies not implemented")
}
func (UnimplementedProxyEngineServer) mustEmbedUnimplementedProxyEngineServer() {}
func (UnimplementedProxyEngineServer) testEmbeddedByValue()                     {}

// UnsafeProxyEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyEngineServer will
// result in compilation errors.
type UnsafeProxyEngineServer interface {
	mustEmbedUnimplementedProxyEngineServer()
}

func RegisterProxyEngineServer(s grpc.ServiceRegistrar, srv ProxyEngineServer) {
	// If the following call panics, it indicates UnimplementedProxyEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyEngine_ServiceDesc, srv)
}

func _ProxyEngine_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetActiveProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetActiveProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetActiveProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetActiveProxy(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_StreamProxyUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyEngineServer).StreamProxyUpdates(m, &grpc.GenericServerStream[Empty, ProxyUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyEngine_StreamProxyUpdatesServer = grpc.ServerStreamingServer[ProxyUpdate]

func _ProxyEngine_GetRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetRegions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetEngineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetEngineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetEngineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetEngineStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetPoolSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetPoolSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetPoolSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetPoolSummary(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetProxies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetProxies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetProxies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetProxies(ctx, req.(*GetProxiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_ReportUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).ReportUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_ReportUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).ReportUsage(ctx, req.(*UsageReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetBlockStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetBlockStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetBlockStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetBlockStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_ToggleAdBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).ToggleAdBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_ToggleAdBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).ToggleAdBlock(ctx, req.(*ToggleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_CheckDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).CheckDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_CheckDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).CheckDomain(ctx, req.(*DomainCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).RefreshToken(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).UpdateConfig(ctx, req.(*ConfigUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetAnalyticsSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetAnalyticsSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetAnalyticsSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetAnalyticsSummary(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyEngine_GetTopProxies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopProxiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyEngineServer).GetTopProxies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyEngine_GetTopProxies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyEngineServer).GetTopProxies(ctx, req.(*TopProxiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyEngine_ServiceDesc is the grpc.ServiceDesc for ProxyEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.v1.ProxyEngine",
	HandlerType: (*ProxyEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _ProxyEngine_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _ProxyEngine_Disconnect_Handler,
		},
		{
			MethodName: "GetActiveProxy",
			Handler:    _ProxyEngine_GetActiveProxy_Handler,
		},
		{
			MethodName: "GetRegions",
			Handler:    _ProxyEngine_GetRegions_Handler,
		},
		{
			MethodName: "GetEngineStatus",
			Handler:    _ProxyEngine_GetEngineStatus_Handler,
		},
		{
			MethodName: "GetPoolSummary",
			Handler:    _ProxyEngine_GetPoolSummary_Handler,
		},
		{
			MethodName: "GetProxies",
			Handler:    _ProxyEngine_GetProxies_Handler,
		},
		{
			MethodName: "ReportUsage",
			Handler:    _ProxyEngine_ReportUsage_Handler,
		},
		{
			MethodName: "GetBlockStats",
			Handler:    _ProxyEngine_GetBlockStats_Handler,
		},
		{
			MethodName: "ToggleAdBlock",
			Handler:    _ProxyEngine_ToggleAdBlock_Handler,
		},
		{
			MethodName: "CheckDomain",
			Handler:    _ProxyEngine_CheckDomain_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _ProxyEngine_Authenticate_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _ProxyEngine_RefreshToken_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ProxyEngine_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _ProxyEngine_UpdateConfig_Handler,
		},
		{
			MethodName: "GetAnalyticsSummary",
			Handler:    _ProxyEngine_GetAnalyticsSummary_Handler,
		},
		{
			MethodName: "GetTopProxies",
			Handler:    _ProxyEngine_GetTopProxies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProxyUpdates",
			Handler:       _ProxyEngine_StreamProxyUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "engine.proto",
}
