// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ═══════════════════════════════════════════════════════════
// Proxy Types
// ═══════════════════════════════════════════════════════════
type ProxyProtocol int32

const (
	ProxyProtocol_PROXY_PROTOCOL_UNSPECIFIED ProxyProtocol = 0
	ProxyProtocol_PROXY_PROTOCOL_SOCKS5      ProxyProtocol = 1
	ProxyProtocol_PROXY_PROTOCOL_SOCKS4      ProxyProtocol = 2
	ProxyProtocol_PROXY_PROTOCOL_HTTP        ProxyProtocol = 3
	ProxyProtocol_PROXY_PROTOCOL_HTTPS       ProxyProtocol = 4
)

// Enum value maps for ProxyProtocol.
var (
	ProxyProtocol_name = map[int32]string{
		0: "PROXY_PROTOCOL_UNSPECIFIED",
		1: "PROXY_PROTOCOL_SOCKS5",
		2: "PROXY_PROTOCOL_SOCKS4",
		3: "PROXY_PROTOCOL_HTTP",
		4: "PROXY_PROTOCOL_HTTPS",
	}
	ProxyProtocol_value = map[string]int32{
		"PROXY_PROTOCOL_UNSPECIFIED": 0,
		"PROXY_PROTOCOL_SOCKS5":      1,
		"PROXY_PROTOCOL_SOCKS4":      2,
		"PROXY_PROTOCOL_HTTP":        3,
		"PROXY_PROTOCOL_HTTPS":       4,
	}
)

func (x ProxyProtocol) Enum() *ProxyProtocol {
	p := new(ProxyProtocol)
	*p = x
	return p
}

func (x ProxyProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[0].Descriptor()
}

func (ProxyProtocol) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[0]
}

func (x ProxyProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyProtocol.Descriptor instead.
func (ProxyProtocol) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type ProxyStatus int32

const (
	ProxyStatus_PROXY_STATUS_UNSPECIFIED ProxyStatus = 0
	ProxyStatus_PROXY_STATUS_ALIVE       ProxyStatus = 1
	ProxyStatus_PROXY_STATUS_DEAD        ProxyStatus = 2
	ProxyStatus_PROXY_STATUS_CHECKING    ProxyStatus = 3
	ProxyStatus_PROXY_STATUS_BLACKLISTED ProxyStatus = 4
	ProxyStatus_PROXY_STATUS_UNCHECKED   ProxyStatus = 5
)

// Enum value maps for ProxyStatus.
var (
	ProxyStatus_name = map[int32]string{
		0: "PROXY_STATUS_UNSPECIFIED",
		1: "PROXY_STATUS_ALIVE",
		2: "PROXY_STATUS_DEAD",
		3: "PROXY_STATUS_CHECKING",
		4: "PROXY_STATUS_BLACKLISTED",
		5: "PROXY_STATUS_UNCHECKED",
	}
	ProxyStatus_value = map[string]int32{
		"PROXY_STATUS_UNSPECIFIED": 0,
		"PROXY_STATUS_ALIVE":       1,
		"PROXY_STATUS_DEAD":        2,
		"PROXY_STATUS_CHECKING":    3,
		"PROXY_STATUS_BLACKLISTED": 4,
		"PROXY_STATUS_UNCHECKED":   5,
	}
)

func (x ProxyStatus) Enum() *ProxyStatus {
	p := new(ProxyStatus)
	*p = x
	return p
}

func (x ProxyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[1].Descriptor()
}

func (ProxyStatus) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[1]
}

func (x ProxyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyStatus.Descriptor instead.
func (ProxyStatus) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

// ═══════════════════════════════════════════════════════════
// Streaming Updates
// ═══════════════════════════════════════════════════════════
type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED       UpdateType = 0
	UpdateType_UPDATE_TYPE_PROXY_CHANGED     UpdateType = 1
	UpdateType_UPDATE_TYPE_PROXY_DOWN        UpdateType = 2
	UpdateType_UPDATE_TYPE_POOL_UPDATED      UpdateType = 3
	UpdateType_UPDATE_TYPE_BANDWIDTH_WARNING UpdateType = 4
	UpdateType_UPDATE_TYPE_ENGINE_STOPPED    UpdateType = 5
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNSPECIFIED",
		1: "UPDATE_TYPE_PROXY_CHANGED",
		2: "UPDATE_TYPE_PROXY_DOWN",
		3: "UPDATE_TYPE_POOL_UPDATED",
		4: "UPDATE_TYPE_BANDWIDTH_WARNING",
		5: "UPDATE_TYPE_ENGINE_STOPPED",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED":       0,
		"UPDATE_TYPE_PROXY_CHANGED":     1,
		"UPDATE_TYPE_PROXY_DOWN":        2,
		"UPDATE_TYPE_POOL_UPDATED":      3,
		"UPDATE_TYPE_BANDWIDTH_WARNING": 4,
		"UPDATE_TYPE_ENGINE_STOPPED":    5,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[2].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[2]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

// ═══════════════════════════════════════════════════════════
// Common
// ═══════════════════════════════════════════════════════════
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type ProxyInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                  string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol            ProxyProtocol          `protobuf:"varint,4,opt,name=protocol,proto3,enum=engine.v1.ProxyProtocol" json:"protocol,omitempty"`
	Country             string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	City                string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Status              ProxyStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=engine.v1.ProxyStatus" json:"status,omitempty"`
	SpeedMs             float64                `protobuf:"fixed64,8,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"`
	Score               float64                `protobuf:"fixed64,9,opt,name=score,proto3" json:"score,omitempty"`
	SslVerified         bool                   `protobuf:"varint,10,opt,name=ssl_verified,json=sslVerified,proto3" json:"ssl_verified,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,11,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	IsActive            bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Username            string                 `protobuf:"bytes,13,opt,name=username,proto3" json:"username,omitempty"`
	Password            string                 `protobuf:"bytes,14,opt,name=password,proto3" json:"password,omitempty"`
	LastChecked         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProxyInfo) Reset() {
	*x = ProxyInfo{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInfo) ProtoMessage() {}

func (x *ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInfo.ProtoReflect.Descriptor instead.
func (*ProxyInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ProxyInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyInfo) GetProtocol() ProxyProtocol {
	if x != nil {
		return x.Protocol
	}
	return ProxyProtocol_PROXY_PROTOCOL_UNSPECIFIED
}

func (x *ProxyInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ProxyInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProxyInfo) GetStatus() ProxyStatus {
	if x != nil {
		return x.Status
	}
	return ProxyStatus_PROXY_STATUS_UNSPECIFIED
}

func (x *ProxyInfo) GetSpeedMs() float64 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

func (x *ProxyInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProxyInfo) GetSslVerified() bool {
	if x != nil {
		return x.SslVerified
	}
	return false
}

func (x *ProxyInfo) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *ProxyInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProxyInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProxyInfo) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

// ═══════════════════════════════════════════════════════════
// Connect / Disconnect
// ═══════════════════════════════════════════════════════════
type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ConnectRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ActiveProxy   *ProxyInfo             `protobuf:"bytes,3,opt,name=active_proxy,json=activeProxy,proto3" json:"active_proxy,omitempty"`
	RelayHost     string                 `protobuf:"bytes,4,opt,name=relay_host,json=relayHost,proto3" json:"relay_host,omitempty"`
	RelayPort     int32                  `protobuf:"varint,5,opt,name=relay_port,json=relayPort,proto3" json:"relay_port,omitempty"`
	SessionToken  string                 `protobuf:"bytes,6,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectResponse) GetActiveProxy() *ProxyInfo {
	if x != nil {
		return x.ActiveProxy
	}
	return nil
}

func (x *ConnectResponse) GetRelayHost() string {
	if x != nil {
		return x.RelayHost
	}
	return ""
}

func (x *ConnectResponse) GetRelayPort() int32 {
	if x != nil {
		return x.RelayPort
	}
	return 0
}

func (x *ConnectResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ConnectResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProxyUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UpdateType             `protobuf:"varint,1,opt,name=type,proto3,enum=engine.v1.UpdateType" json:"type,omitempty"`
	Proxy         *ProxyInfo             `protobuf:"bytes,2,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Pool          *PoolSummary           `protobuf:"bytes,3,opt,name=pool,proto3" json:"pool,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyUpdate) Reset() {
	*x = ProxyUpdate{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyUpdate) ProtoMessage() {}

func (x *ProxyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyUpdate.ProtoReflect.Descriptor instead.
func (*ProxyUpdate) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ProxyUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

func (x *ProxyUpdate) GetProxy() *ProxyInfo {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *ProxyUpdate) GetPool() *PoolSummary {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *ProxyUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProxyUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ═══════════════════════════════════════════════════════════
// Regions
// ═══════════════════════════════════════════════════════════
type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServerCount   int32                  `protobuf:"varint,3,opt,name=server_count,json=serverCount,proto3" json:"server_count,omitempty"`
	LoadPct       int32                  `protobuf:"varint,4,opt,name=load_pct,json=loadPct,proto3" json:"load_pct,omitempty"`
	AvgLatencyMs  int32                  `protobuf:"varint,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	Available     bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	LockedReason  string                 `protobuf:"bytes,7,opt,name=locked_reason,json=lockedReason,proto3" json:"locked_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *Region) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Region) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Region) GetServerCount() int32 {
	if x != nil {
		return x.ServerCount
	}
	return 0
}

func (x *Region) GetLoadPct() int32 {
	if x != nil {
		return x.LoadPct
	}
	return 0
}

func (x *Region) GetAvgLatencyMs() int32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *Region) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Region) GetLockedReason() string {
	if x != nil {
		return x.LockedReason
	}
	return ""
}

type RegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*Region              `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	CurrentRegion string                 `protobuf:"bytes,2,opt,name=current_region,json=currentRegion,proto3" json:"current_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionsResponse) Reset() {
	*x = RegionsResponse{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionsResponse) ProtoMessage() {}

func (x *RegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionsResponse.ProtoReflect.Descriptor instead.
func (*RegionsResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *RegionsResponse) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *RegionsResponse) GetCurrentRegion() string {
	if x != nil {
		return x.CurrentRegion
	}
	return ""
}

// ═══════════════════════════════════════════════════════════
// Engine Status
// ═══════════════════════════════════════════════════════════
type EngineStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Starting      bool                   `protobuf:"varint,2,opt,name=starting,proto3" json:"starting,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Socks5Port    int32                  `protobuf:"varint,4,opt,name=socks5_port,json=socks5Port,proto3" json:"socks5_port,omitempty"`
	HttpPort      int32                  `protobuf:"varint,5,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`
	Socks5Ok      bool                   `protobuf:"varint,6,opt,name=socks5_ok,json=socks5Ok,proto3" json:"socks5_ok,omitempty"`
	HttpOk        bool                   `protobuf:"varint,7,opt,name=http_ok,json=httpOk,proto3" json:"http_ok,omitempty"`
	AuthEnabled   bool                   `protobuf:"varint,8,opt,name=auth_enabled,json=authEnabled,proto3" json:"auth_enabled,omitempty"`
	LocalIps      []string               `protobuf:"bytes,9,rep,name=local_ips,json=localIps,proto3" json:"local_ips,omitempty"`
	ActiveProxy   *ProxyInfo             `protobuf:"bytes,10,opt,name=active_proxy,json=activeProxy,proto3" json:"active_proxy,omitempty"`
	Pool          *PoolSummary           `protobuf:"bytes,11,opt,name=pool,proto3" json:"pool,omitempty"`
	Discovery     *DiscoveryStatus       `protobuf:"bytes,12,opt,name=discovery,proto3" json:"discovery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineStatus) Reset() {
	*x = EngineStatus{}
	mi := &file_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStatus) ProtoMessage() {}

func (x *EngineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStatus.ProtoReflect.Descriptor instead.
func (*EngineStatus) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

func (x *EngineStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *EngineStatus) GetStarting() bool {
	if x != nil {
		return x.Starting
	}
	return false
}

func (x *EngineStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *EngineStatus) GetSocks5Port() int32 {
	if x != nil {
		return x.Socks5Port
	}
	return 0
}

func (x *EngineStatus) GetHttpPort() int32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

func (x *EngineStatus) GetSocks5Ok() bool {
	if x != nil {
		return x.Socks5Ok
	}
	return false
}

func (x *EngineStatus) GetHttpOk() bool {
	if x != nil {
		return x.HttpOk
	}
	return false
}

func (x *EngineStatus) GetAuthEnabled() bool {
	if x != nil {
		return x.AuthEnabled
	}
	return false
}

func (x *EngineStatus) GetLocalIps() []string {
	if x != nil {
		return x.LocalIps
	}
	return nil
}

func (x *EngineStatus) GetActiveProxy() *ProxyInfo {
	if x != nil {
		return x.ActiveProxy
	}
	return nil
}

func (x *EngineStatus) GetPool() *PoolSummary {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *EngineStatus) GetDiscovery() *DiscoveryStatus {
	if x != nil {
		return x.Discovery
	}
	return nil
}

type DiscoveryStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Paused         bool                   `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	Round          int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Checked        int32                  `protobuf:"varint,4,opt,name=checked,proto3" json:"checked,omitempty"`
	AliveFound     int32                  `protobuf:"varint,5,opt,name=alive_found,json=aliveFound,proto3" json:"alive_found,omitempty"`
	TotalUnchecked int32                  `protobuf:"varint,6,opt,name=total_unchecked,json=totalUnchecked,proto3" json:"total_unchecked,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiscoveryStatus) Reset() {
	*x = DiscoveryStatus{}
	mi := &file_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryStatus) ProtoMessage() {}

func (x *DiscoveryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryStatus.ProtoReflect.Descriptor instead.
func (*DiscoveryStatus) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoveryStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DiscoveryStatus) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *DiscoveryStatus) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *DiscoveryStatus) GetChecked() int32 {
	if x != nil {
		return x.Checked
	}
	return 0
}

func (x *DiscoveryStatus) GetAliveFound() int32 {
	if x != nil {
		return x.AliveFound
	}
	return 0
}

func (x *DiscoveryStatus) GetTotalUnchecked() int32 {
	if x != nil {
		return x.TotalUnchecked
	}
	return 0
}

type PoolSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Alive         int32                  `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Dead          int32                  `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"`
	DeadRetryable int32                  `protobuf:"varint,4,opt,name=dead_retryable,json=deadRetryable,proto3" json:"dead_retryable,omitempty"`
	Blacklisted   int32                  `protobuf:"varint,5,opt,name=blacklisted,proto3" json:"blacklisted,omitempty"`
	Unchecked     int32                  `protobuf:"varint,6,opt,name=unchecked,proto3" json:"unchecked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolSummary) Reset() {
	*x = PoolSummary{}
	mi := &file_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolSummary) ProtoMessage() {}

func (x *PoolSummary) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolSummary.ProtoReflect.Descriptor instead.
func (*PoolSummary) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *PoolSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PoolSummary) GetAlive() int32 {
	if x != nil {
		return x.Alive
	}
	return 0
}

func (x *PoolSummary) GetDead() int32 {
	if x != nil {
		return x.Dead
	}
	return 0
}

func (x *PoolSummary) GetDeadRetryable() int32 {
	if x != nil {
		return x.DeadRetryable
	}
	return 0
}

func (x *PoolSummary) GetBlacklisted() int32 {
	if x != nil {
		return x.Blacklisted
	}
	return 0
}

func (x *PoolSummary) GetUnchecked() int32 {
	if x != nil {
		return x.Unchecked
	}
	return 0
}

// ═══════════════════════════════════════════════════════════
// Proxies List
// ═══════════════════════════════════════════════════════════
type GetProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	CountryFilter string                 `protobuf:"bytes,2,opt,name=country_filter,json=countryFilter,proto3" json:"country_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxiesRequest) Reset() {
	*x = GetProxiesRequest{}
	mi := &file_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxiesRequest) ProtoMessage() {}

func (x *GetProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxiesRequest.ProtoReflect.Descriptor instead.
func (*GetProxiesRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12}
}

func (x *GetProxiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProxiesRequest) GetCountryFilter() string {
	if x != nil {
		return x.CountryFilter
	}
	return ""
}

type ProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxies       []*ProxyInfo           `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxiesResponse) Reset() {
	*x = ProxiesResponse{}
	mi := &file_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxiesResponse) ProtoMessage() {}

func (x *ProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxiesResponse.ProtoReflect.Descriptor instead.
func (*ProxiesResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{13}
}

func (x *ProxiesResponse) GetProxies() []*ProxyInfo {
	if x != nil {
		return x.Proxies
	}
	return nil
}

// ═══════════════════════════════════════════════════════════
// Usage
// ═══════════════════════════════════════════════════════════
type UsageReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BytesUp         int64                  `protobuf:"varint,2,opt,name=bytes_up,json=bytesUp,proto3" json:"bytes_up,omitempty"`
	BytesDown       int64                  `protobuf:"varint,3,opt,name=bytes_down,json=bytesDown,proto3" json:"bytes_down,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{14}
}

func (x *UsageReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UsageReport) GetBytesUp() int64 {
	if x != nil {
		return x.BytesUp
	}
	return 0
}

func (x *UsageReport) GetBytesDown() int64 {
	if x != nil {
		return x.BytesDown
	}
	return 0
}

func (x *UsageReport) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type UsageResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Status               string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BandwidthRemainingGb float64                `protobuf:"fixed64,2,opt,name=bandwidth_remaining_gb,json=bandwidthRemainingGb,proto3" json:"bandwidth_remaining_gb,omitempty"`
	Action               string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UsageResponse) Reset() {
	*x = UsageResponse{}
	mi := &file_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResponse) ProtoMessage() {}

func (x *UsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResponse.ProtoReflect.Descriptor instead.
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{15}
}

func (x *UsageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UsageResponse) GetBandwidthRemainingGb() float64 {
	if x != nil {
		return x.BandwidthRemainingGb
	}
	return 0
}

func (x *UsageResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// ═══════════════════════════════════════════════════════════
// AdBlock
// ═══════════════════════════════════════════════════════════
type BlockStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TotalBlocked      int64                  `protobuf:"varint,2,opt,name=total_blocked,json=totalBlocked,proto3" json:"total_blocked,omitempty"`
	RulesCount        int32                  `protobuf:"varint,3,opt,name=rules_count,json=rulesCount,proto3" json:"rules_count,omitempty"`
	WhitelistCount    int32                  `protobuf:"varint,4,opt,name=whitelist_count,json=whitelistCount,proto3" json:"whitelist_count,omitempty"`
	CategoriesEnabled map[string]bool        `protobuf:"bytes,5,rep,name=categories_enabled,json=categoriesEnabled,proto3" json:"categories_enabled,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlockStats) Reset() {
	*x = BlockStats{}
	mi := &file_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockStats) ProtoMessage() {}

func (x *BlockStats) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockStats.ProtoReflect.Descriptor instead.
func (*BlockStats) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{16}
}

func (x *BlockStats) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BlockStats) GetTotalBlocked() int64 {
	if x != nil {
		return x.TotalBlocked
	}
	return 0
}

func (x *BlockStats) GetRulesCount() int32 {
	if x != nil {
		return x.RulesCount
	}
	return 0
}

func (x *BlockStats) GetWhitelistCount() int32 {
	if x != nil {
		return x.WhitelistCount
	}
	return 0
}

func (x *BlockStats) GetCategoriesEnabled() map[string]bool {
	if x != nil {
		return x.CategoriesEnabled
	}
	return nil
}

type ToggleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleRequest) Reset() {
	*x = ToggleRequest{}
	mi := &file_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleRequest) ProtoMessage() {}

func (x *ToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleRequest.ProtoReflect.Descriptor instead.
func (*ToggleRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{17}
}

func (x *ToggleRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ToggleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ToggleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleResponse) Reset() {
	*x = ToggleResponse{}
	mi := &file_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleResponse) ProtoMessage() {}

func (x *ToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleResponse.ProtoReflect.Descriptor instead.
func (*ToggleResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{18}
}

func (x *ToggleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToggleResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DomainCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainCheckRequest) Reset() {
	*x = DomainCheckRequest{}
	mi := &file_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainCheckRequest) ProtoMessage() {}

func (x *DomainCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainCheckRequest.ProtoReflect.Descriptor instead.
func (*DomainCheckRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{19}
}

func (x *DomainCheckRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type DomainCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocked       bool                   `protobuf:"varint,1,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	MatchedRule   string                 `protobuf:"bytes,3,opt,name=matched_rule,json=matchedRule,proto3" json:"matched_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainCheckResponse) Reset() {
	*x = DomainCheckResponse{}
	mi := &file_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainCheckResponse) ProtoMessage() {}

func (x *DomainCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainCheckResponse.ProtoReflect.Descriptor instead.
func (*DomainCheckResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{20}
}

func (x *DomainCheckResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *DomainCheckResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DomainCheckResponse) GetMatchedRule() string {
	if x != nil {
		return x.MatchedRule
	}
	return ""
}

// ═══════════════════════════════════════════════════════════
// Auth
// ═══════════════════════════════════════════════════════════
type AuthRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password          string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceFingerprint string                 `protobuf:"bytes,3,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	DeviceName        string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceOs          string                 `protobuf:"bytes,5,opt,name=device_os,json=deviceOs,proto3" json:"device_os,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{21}
}

func (x *AuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRequest) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *AuthRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AuthRequest) GetDeviceOs() string {
	if x != nil {
		return x.DeviceOs
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	User          *UserInfo              `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{22}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AuthResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{23}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Plan                 string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	BandwidthRemainingGb float64                `protobuf:"fixed64,5,opt,name=bandwidth_remaining_gb,json=bandwidthRemainingGb,proto3" json:"bandwidth_remaining_gb,omitempty"`
	MaxDevices           int32                  `protobuf:"varint,6,opt,name=max_devices,json=maxDevices,proto3" json:"max_devices,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{24}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *UserInfo) GetBandwidthRemainingGb() float64 {
	if x != nil {
		return x.BandwidthRemainingGb
	}
	return 0
}

func (x *UserInfo) GetMaxDevices() int32 {
	if x != nil {
		return x.MaxDevices
	}
	return 0
}

// ═══════════════════════════════════════════════════════════
// Config
// ═══════════════════════════════════════════════════════════
type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_engine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{25}
}

func (x *ConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       map[string]string      `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdateRequest) Reset() {
	*x = ConfigUpdateRequest{}
	mi := &file_engine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdateRequest) ProtoMessage() {}

func (x *ConfigUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdateRequest.ProtoReflect.Descriptor instead.
func (*ConfigUpdateRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{26}
}

func (x *ConfigUpdateRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

// ═══════════════════════════════════════════════════════════
// Analytics
// ═══════════════════════════════════════════════════════════
type AnalyticsSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTracked  int32                  `protobuf:"varint,1,opt,name=total_tracked,json=totalTracked,proto3" json:"total_tracked,omitempty"`
	AvgSpeedMs    float64                `protobuf:"fixed64,2,opt,name=avg_speed_ms,json=avgSpeedMs,proto3" json:"avg_speed_ms,omitempty"`
	AvgUptimePct  float64                `protobuf:"fixed64,3,opt,name=avg_uptime_pct,json=avgUptimePct,proto3" json:"avg_uptime_pct,omitempty"`
	BestProxy     *ProxyInfo             `protobuf:"bytes,4,opt,name=best_proxy,json=bestProxy,proto3" json:"best_proxy,omitempty"`
	WorstProxy    *ProxyInfo             `protobuf:"bytes,5,opt,name=worst_proxy,json=worstProxy,proto3" json:"worst_proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsSummary) Reset() {
	*x = AnalyticsSummary{}
	mi := &file_engine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsSummary) ProtoMessage() {}

func (x *AnalyticsSummary) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsSummary.ProtoReflect.Descriptor instead.
func (*AnalyticsSummary) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{27}
}

func (x *AnalyticsSummary) GetTotalTracked() int32 {
	if x != nil {
		return x.TotalTracked
	}
	return 0
}

func (x *AnalyticsSummary) GetAvgSpeedMs() float64 {
	if x != nil {
		return x.AvgSpeedMs
	}
	return 0
}

func (x *AnalyticsSummary) GetAvgUptimePct() float64 {
	if x != nil {
		return x.AvgUptimePct
	}
	return 0
}

func (x *AnalyticsSummary) GetBestProxy() *ProxyInfo {
	if x != nil {
		return x.BestProxy
	}
	return nil
}

func (x *AnalyticsSummary) GetWorstProxy() *ProxyInfo {
	if x != nil {
		return x.WorstProxy
	}
	return nil
}

type TopProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopProxiesRequest) Reset() {
	*x = TopProxiesRequest{}
	mi := &file_engine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProxiesRequest) ProtoMessage() {}

func (x *TopProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProxiesRequest.ProtoReflect.Descriptor instead.
func (*TopProxiesRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{28}
}

func (x *TopProxiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxies       []*ProxyInfo           `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopProxiesResponse) Reset() {
	*x = TopProxiesResponse{}
	mi := &file_engine_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProxiesResponse) ProtoMessage() {}

func (x *TopProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProxiesResponse.ProtoReflect.Descriptor instead.
func (*TopProxiesResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{29}
}

func (x *TopProxiesResponse) GetProxies() []*ProxyInfo {
	if x != nil {
		return x.Proxies
	}
	return nil
}

// ═══════════════════════════════════════════════════════════
// Rotation
// ═══════════════════════════════════════════════════════════
type RotationStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PoolSize        int32                  `protobuf:"varint,2,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	CurrentIndex    int32                  `protobuf:"varint,3,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	ActiveProxyIp   string                 `protobuf:"bytes,4,opt,name=active_proxy_ip,json=activeProxyIp,proto3" json:"active_proxy_ip,omitempty"`
	ActiveProxyPort int32                  `protobuf:"varint,5,opt,name=active_proxy_port,json=activeProxyPort,proto3" json:"active_proxy_port,omitempty"`
	ActiveProxyType string                 `protobuf:"bytes,6,opt,name=active_proxy_type,json=activeProxyType,proto3" json:"active_proxy_type,omitempty"`
	IntervalSec     int32                  `protobuf:"varint,7,opt,name=interval_sec,json=intervalSec,proto3" json:"interval_sec,omitempty"`
	ProxyTypes      []string               `protobuf:"bytes,8,rep,name=proxy_types,json=proxyTypes,proto3" json:"proxy_types,omitempty"`
	CountryFilter   string                 `protobuf:"bytes,9,opt,name=country_filter,json=countryFilter,proto3" json:"country_filter,omitempty"`
	MaxSpeedMs      int32                  `protobuf:"varint,10,opt,name=max_speed_ms,json=maxSpeedMs,proto3" json:"max_speed_ms,omitempty"`
	SslOnly         bool                   `protobuf:"varint,11,opt,name=ssl_only,json=sslOnly,proto3" json:"ssl_only,omitempty"`
	FilteredCount   int32                  `protobuf:"varint,12,opt,name=filtered_count,json=filteredCount,proto3" json:"filtered_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RotationStatus) Reset() {
	*x = RotationStatus{}
	mi := &file_engine_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationStatus) ProtoMessage() {}

func (x *RotationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationStatus.ProtoReflect.Descriptor instead.
func (*RotationStatus) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{30}
}

func (x *RotationStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RotationStatus) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *RotationStatus) GetCurrentIndex() int32 {
	if x != nil {
		return x.CurrentIndex
	}
	return 0
}

func (x *RotationStatus) GetActiveProxyIp() string {
	if x != nil {
		return x.ActiveProxyIp
	}
	return ""
}

func (x *RotationStatus) GetActiveProxyPort() int32 {
	if x != nil {
		return x.ActiveProxyPort
	}
	return 0
}

func (x *RotationStatus) GetActiveProxyType() string {
	if x != nil {
		return x.ActiveProxyType
	}
	return ""
}

func (x *RotationStatus) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *RotationStatus) GetProxyTypes() []string {
	if x != nil {
		return x.ProxyTypes
	}
	return nil
}

func (x *RotationStatus) GetCountryFilter() string {
	if x != nil {
		return x.CountryFilter
	}
	return ""
}

func (x *RotationStatus) GetMaxSpeedMs() int32 {
	if x != nil {
		return x.MaxSpeedMs
	}
	return 0
}

func (x *RotationStatus) GetSslOnly() bool {
	if x != nil {
		return x.SslOnly
	}
	return false
}

func (x *RotationStatus) GetFilteredCount() int32 {
	if x != nil {
		return x.FilteredCount
	}
	return 0
}

type RotationPoolItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Ping          float64                `protobuf:"fixed64,5,opt,name=ping,proto3" json:"ping,omitempty"`
	Ssl           bool                   `protobuf:"varint,6,opt,name=ssl,proto3" json:"ssl,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationPoolItem) Reset() {
	*x = RotationPoolItem{}
	mi := &file_engine_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationPoolItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationPoolItem) ProtoMessage() {}

func (x *RotationPoolItem) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationPoolItem.ProtoReflect.Descriptor instead.
func (*RotationPoolItem) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{31}
}

func (x *RotationPoolItem) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RotationPoolItem) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RotationPoolItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RotationPoolItem) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RotationPoolItem) GetPing() float64 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *RotationPoolItem) GetSsl() bool {
	if x != nil {
		return x.Ssl
	}
	return false
}

func (x *RotationPoolItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RotationPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxies       []*RotationPoolItem    `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationPoolResponse) Reset() {
	*x = RotationPoolResponse{}
	mi := &file_engine_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationPoolResponse) ProtoMessage() {}

func (x *RotationPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationPoolResponse.ProtoReflect.Descriptor instead.
func (*RotationPoolResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{32}
}

func (x *RotationPoolResponse) GetProxies() []*RotationPoolItem {
	if x != nil {
		return x.Proxies
	}
	return nil
}

type RotationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalSec   int32                  `protobuf:"varint,1,opt,name=interval_sec,json=intervalSec,proto3" json:"interval_sec,omitempty"`
	ProxyTypes    []string               `protobuf:"bytes,2,rep,name=proxy_types,json=proxyTypes,proto3" json:"proxy_types,omitempty"`
	CountryFilter string                 `protobuf:"bytes,3,opt,name=country_filter,json=countryFilter,proto3" json:"country_filter,omitempty"`
	MaxSpeedMs    int32                  `protobuf:"varint,4,opt,name=max_speed_ms,json=maxSpeedMs,proto3" json:"max_speed_ms,omitempty"`
	PoolSize      int32                  `protobuf:"varint,5,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	SslOnly       bool                   `protobuf:"varint,6,opt,name=ssl_only,json=sslOnly,proto3" json:"ssl_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationConfig) Reset() {
	*x = RotationConfig{}
	mi := &file_engine_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationConfig) ProtoMessage() {}

func (x *RotationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationConfig.ProtoReflect.Descriptor instead.
func (*RotationConfig) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{33}
}

func (x *RotationConfig) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *RotationConfig) GetProxyTypes() []string {
	if x != nil {
		return x.ProxyTypes
	}
	return nil
}

func (x *RotationConfig) GetCountryFilter() string {
	if x != nil {
		return x.CountryFilter
	}
	return ""
}

func (x *RotationConfig) GetMaxSpeedMs() int32 {
	if x != nil {
		return x.MaxSpeedMs
	}
	return 0
}

func (x *RotationConfig) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *RotationConfig) GetSslOnly() bool {
	if x != nil {
		return x.SslOnly
	}
	return false
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\tengine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xee\x03\n" +
	"\tProxyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x124\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x18.engine.v1.ProxyProtocolR\bprotocol\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.engine.v1.ProxyStatusR\x06status\x12\x19\n" +
	"\bspeed_ms\x18\b \x01(\x01R\aspeedMs\x12\x14\n" +
	"\x05score\x18\t \x01(\x01R\x05score\x12!\n" +
	"\fssl_verified\x18\n" +
	" \x01(\bR\vsslVerified\x121\n" +
	"\x14consecutive_failures\x18\v \x01(\x05R\x13consecutiveFailures\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12\x1a\n" +
	"\busername\x18\r \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x0e \x01(\tR\bpassword\x12=\n" +
	"\flast_checked\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vlastChecked\"D\n" +
	"\x0eConnectRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\"\xb7\x02\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x127\n" +
	"\factive_proxy\x18\x03 \x01(\v2\x14.engine.v1.ProxyInfoR\vactiveProxy\x12\x1d\n" +
	"\n" +
	"relay_host\x18\x04 \x01(\tR\trelayHost\x12\x1d\n" +
	"\n" +
	"relay_port\x18\x05 \x01(\x05R\trelayPort\x12#\n" +
	"\rsession_token\x18\x06 \x01(\tR\fsessionToken\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"2\n" +
	"\x11DisconnectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe4\x01\n" +
	"\vProxyUpdate\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.engine.v1.UpdateTypeR\x04type\x12*\n" +
	"\x05proxy\x18\x02 \x01(\v2\x14.engine.v1.ProxyInfoR\x05proxy\x12*\n" +
	"\x04pool\x18\x03 \x01(\v2\x16.engine.v1.PoolSummaryR\x04pool\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd7\x01\n" +
	"\x06Region\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fserver_count\x18\x03 \x01(\x05R\vserverCount\x12\x19\n" +
	"\bload_pct\x18\x04 \x01(\x05R\aloadPct\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x05R\favgLatencyMs\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable\x12#\n" +
	"\rlocked_reason\x18\a \x01(\tR\flockedReason\"e\n" +
	"\x0fRegionsResponse\x12+\n" +
	"\aregions\x18\x01 \x03(\v2\x11.engine.v1.RegionR\aregions\x12%\n" +
	"\x0ecurrent_region\x18\x02 \x01(\tR\rcurrentRegion\"\xab\x03\n" +
	"\fEngineStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1a\n" +
	"\bstarting\x18\x02 \x01(\bR\bstarting\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1f\n" +
	"\vsocks5_port\x18\x04 \x01(\x05R\n" +
	"socks5Port\x12\x1b\n" +
	"\thttp_port\x18\x05 \x01(\x05R\bhttpPort\x12\x1b\n" +
	"\tsocks5_ok\x18\x06 \x01(\bR\bsocks5Ok\x12\x17\n" +
	"\ahttp_ok\x18\a \x01(\bR\x06httpOk\x12!\n" +
	"\fauth_enabled\x18\b \x01(\bR\vauthEnabled\x12\x1b\n" +
	"\tlocal_ips\x18\t \x03(\tR\blocalIps\x127\n" +
	"\factive_proxy\x18\n" +
	" \x01(\v2\x14.engine.v1.ProxyInfoR\vactiveProxy\x12*\n" +
	"\x04pool\x18\v \x01(\v2\x16.engine.v1.PoolSummaryR\x04pool\x128\n" +
	"\tdiscovery\x18\f \x01(\v2\x1a.engine.v1.DiscoveryStatusR\tdiscovery\"\xbd\x01\n" +
	"\x0fDiscoveryStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12\x18\n" +
	"\achecked\x18\x04 \x01(\x05R\achecked\x12\x1f\n" +
	"\valive_found\x18\x05 \x01(\x05R\n" +
	"aliveFound\x12'\n" +
	"\x0ftotal_unchecked\x18\x06 \x01(\x05R\x0etotalUnchecked\"\xb4\x01\n" +
	"\vPoolSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\x05R\x05alive\x12\x12\n" +
	"\x04dead\x18\x03 \x01(\x05R\x04dead\x12%\n" +
	"\x0edead_retryable\x18\x04 \x01(\x05R\rdeadRetryable\x12 \n" +
	"\vblacklisted\x18\x05 \x01(\x05R\vblacklisted\x12\x1c\n" +
	"\tunchecked\x18\x06 \x01(\x05R\tunchecked\"P\n" +
	"\x11GetProxiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12%\n" +
	"\x0ecountry_filter\x18\x02 \x01(\tR\rcountryFilter\"A\n" +
	"\x0fProxiesResponse\x12.\n" +
	"\aproxies\x18\x01 \x03(\v2\x14.engine.v1.ProxyInfoR\aproxies\"\x91\x01\n" +
	"\vUsageReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bbytes_up\x18\x02 \x01(\x03R\abytesUp\x12\x1d\n" +
	"\n" +
	"bytes_down\x18\x03 \x01(\x03R\tbytesDown\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\"u\n" +
	"\rUsageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x124\n" +
	"\x16bandwidth_remaining_gb\x18\x02 \x01(\x01R\x14bandwidthRemainingGb\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\xb8\x02\n" +
	"\n" +
	"BlockStats\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rtotal_blocked\x18\x02 \x01(\x03R\ftotalBlocked\x12\x1f\n" +
	"\vrules_count\x18\x03 \x01(\x05R\n" +
	"rulesCount\x12'\n" +
	"\x0fwhitelist_count\x18\x04 \x01(\x05R\x0ewhitelistCount\x12[\n" +
	"\x12categories_enabled\x18\x05 \x03(\v2,.engine.v1.BlockStats.CategoriesEnabledEntryR\x11categoriesEnabled\x1aD\n" +
	"\x16CategoriesEnabledEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"E\n" +
	"\rToggleRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"D\n" +
	"\x0eToggleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\",\n" +
	"\x12DomainCheckRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"n\n" +
	"\x13DomainCheckResponse\x12\x18\n" +
	"\ablocked\x18\x01 \x01(\bR\ablocked\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12!\n" +
	"\fmatched_rule\x18\x03 \x01(\tR\vmatchedRule\"\xac\x01\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12-\n" +
	"\x12device_fingerprint\x18\x03 \x01(\tR\x11deviceFingerprint\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1b\n" +
	"\tdevice_os\x18\x05 \x01(\tR\bdeviceOs\"\xce\x01\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12'\n" +
	"\x04user\x18\x05 \x01(\v2\x13.engine.v1.UserInfoR\x04user\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xaf\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan\x124\n" +
	"\x16bandwidth_remaining_gb\x18\x05 \x01(\x01R\x14bandwidthRemainingGb\x12\x1f\n" +
	"\vmax_devices\x18\x06 \x01(\x05R\n" +
	"maxDevices\"\x8a\x01\n" +
	"\x0eConfigResponse\x12=\n" +
	"\x06config\x18\x01 \x03(\v2%.engine.v1.ConfigResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x13ConfigUpdateRequest\x12E\n" +
	"\aupdates\x18\x01 \x03(\v2+.engine.v1.ConfigUpdateRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x10AnalyticsSummary\x12#\n" +
	"\rtotal_tracked\x18\x01 \x01(\x05R\ftotalTracked\x12 \n" +
	"\favg_speed_ms\x18\x02 \x01(\x01R\n" +
	"avgSpeedMs\x12$\n" +
	"\x0eavg_uptime_pct\x18\x03 \x01(\x01R\favgUptimePct\x123\n" +
	"\n" +
	"best_proxy\x18\x04 \x01(\v2\x14.engine.v1.ProxyInfoR\tbestProxy\x125\n" +
	"\vworst_proxy\x18\x05 \x01(\v2\x14.engine.v1.ProxyInfoR\n" +
	"worstProxy\")\n" +
	"\x11TopProxiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"D\n" +
	"\x12TopProxiesResponse\x12.\n" +
	"\aproxies\x18\x01 \x03(\v2\x14.engine.v1.ProxyInfoR\aproxies\"\xbb\x03\n" +
	"\x0eRotationStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tpool_size\x18\x02 \x01(\x05R\bpoolSize\x12#\n" +
	"\rcurrent_index\x18\x03 \x01(\x05R\fcurrentIndex\x12&\n" +
	"\x0factive_proxy_ip\x18\x04 \x01(\tR\ractiveProxyIp\x12*\n" +
	"\x11active_proxy_port\x18\x05 \x01(\x05R\x0factiveProxyPort\x12*\n" +
	"\x11active_proxy_type\x18\x06 \x01(\tR\x0factiveProxyType\x12!\n" +
	"\finterval_sec\x18\a \x01(\x05R\vintervalSec\x12\x1f\n" +
	"\vproxy_types\x18\b \x03(\tR\n" +
	"proxyTypes\x12%\n" +
	"\x0ecountry_filter\x18\t \x01(\tR\rcountryFilter\x12 \n" +
	"\fmax_speed_ms\x18\n" +
	" \x01(\x05R\n" +
	"maxSpeedMs\x12\x19\n" +
	"\bssl_only\x18\v \x01(\bR\asslOnly\x12%\n" +
	"\x0efiltered_count\x18\f \x01(\x05R\rfilteredCount\"\xa0\x01\n" +
	"\x10RotationPoolItem\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04ping\x18\x05 \x01(\x01R\x04ping\x12\x10\n" +
	"\x03ssl\x18\x06 \x01(\bR\x03ssl\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\"M\n" +
	"\x14RotationPoolResponse\x125\n" +
	"\aproxies\x18\x01 \x03(\v2\x1b.engine.v1.RotationPoolItemR\aproxies\"\xd5\x01\n" +
	"\x0eRotationConfig\x12!\n" +
	"\finterval_sec\x18\x01 \x01(\x05R\vintervalSec\x12\x1f\n" +
	"\vproxy_types\x18\x02 \x03(\tR\n" +
	"proxyTypes\x12%\n" +
	"\x0ecountry_filter\x18\x03 \x01(\tR\rcountryFilter\x12 \n" +
	"\fmax_speed_ms\x18\x04 \x01(\x05R\n" +
	"maxSpeedMs\x12\x1b\n" +
	"\tpool_size\x18\x05 \x01(\x05R\bpoolSize\x12\x19\n" +
	"\bssl_only\x18\x06 \x01(\bR\asslOnly*\x98\x01\n" +
	"\rProxyProtocol\x12\x1e\n" +
	"\x1aPROXY_PROTOCOL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROXY_PROTOCOL_SOCKS5\x10\x01\x12\x19\n" +
	"\x15PROXY_PROTOCOL_SOCKS4\x10\x02\x12\x17\n" +
	"\x13PROXY_PROTOCOL_HTTP\x10\x03\x12\x18\n" +
	"\x14PROXY_PROTOCOL_HTTPS\x10\x04*\xaf\x01\n" +
	"\vProxyStatus\x12\x1c\n" +
	"\x18PROXY_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROXY_STATUS_ALIVE\x10\x01\x12\x15\n" +
	"\x11PROXY_STATUS_DEAD\x10\x02\x12\x19\n" +
	"\x15PROXY_STATUS_CHECKING\x10\x03\x12\x1c\n" +
	"\x18PROXY_STATUS_BLACKLISTED\x10\x04\x12\x1a\n" +
	"\x16PROXY_STATUS_UNCHECKED\x10\x05*\xc5\x01\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19UPDATE_TYPE_PROXY_CHANGED\x10\x01\x12\x1a\n" +
	"\x16UPDATE_TYPE_PROXY_DOWN\x10\x02\x12\x1c\n" +
	"\x18UPDATE_TYPE_POOL_UPDATED\x10\x03\x12!\n" +
	"\x1dUPDATE_TYPE_BANDWIDTH_WARNING\x10\x04\x12\x1e\n" +
	"\x1aUPDATE_TYPE_ENGINE_STOPPED\x10\x052\xbf\v\n" +
	"\vProxyEngine\x12@\n" +
	"\aConnect\x12\x19.engine.v1.ConnectRequest\x1a\x1a.engine.v1.ConnectResponse\x12I\n" +
	"\n" +
	"Disconnect\x12\x1c.engine.v1.DisconnectRequest\x1a\x1d.engine.v1.DisconnectResponse\x128\n" +
	"\x0eGetActiveProxy\x12\x10.engine.v1.Empty\x1a\x14.engine.v1.ProxyInfo\x12@\n" +
	"\x12StreamProxyUpdates\x12\x10.engine.v1.Empty\x1a\x16.engine.v1.ProxyUpdate0\x01\x12:\n" +
	"\n" +
	"GetRegions\x12\x10.engine.v1.Empty\x1a\x1a.engine.v1.RegionsResponse\x12<\n" +
	"\x0fGetEngineStatus\x12\x10.engine.v1.Empty\x1a\x17.engine.v1.EngineStatus\x12:\n" +
	"\x0eGetPoolSummary\x12\x10.engine.v1.Empty\x1a\x16.engine.v1.PoolSummary\x12F\n" +
	"\n" +
	"GetProxies\x12\x1c.engine.v1.GetProxiesRequest\x1a\x1a.engine.v1.ProxiesResponse\x12?\n" +
	"\vReportUsage\x12\x16.engine.v1.UsageReport\x1a\x18.engine.v1.UsageResponse\x128\n" +
	"\rGetBlockStats\x12\x10.engine.v1.Empty\x1a\x15.engine.v1.BlockStats\x12D\n" +
	"\rToggleAdBlock\x12\x18.engine.v1.ToggleRequest\x1a\x19.engine.v1.ToggleResponse\x12L\n" +
	"\vCheckDomain\x12\x1d.engine.v1.DomainCheckRequest\x1a\x1e.engine.v1.DomainCheckResponse\x12?\n" +
	"\fAuthenticate\x12\x16.engine.v1.AuthRequest\x1a\x17.engine.v1.AuthResponse\x12B\n" +
	"\fRefreshToken\x12\x19.engine.v1.RefreshRequest\x1a\x17.engine.v1.AuthResponse\x128\n" +
	"\tGetConfig\x12\x10.engine.v1.Empty\x1a\x19.engine.v1.ConfigResponse\x12I\n" +
	"\fUpdateConfig\x12\x1e.engine.v1.ConfigUpdateRequest\x1a\x19.engine.v1.ConfigResponse\x12D\n" +
	"\x13GetAnalyticsSummary\x12\x10.engine.v1.Empty\x1a\x1b.engine.v1.AnalyticsSummary\x12L\n" +
	"\rGetTopProxies\x12\x1c.engine.v1.TopProxiesRequest\x1a\x1d.engine.v1.TopProxiesResponse\x12@\n" +
	"\x11GetRotationStatus\x12\x10.engine.v1.Empty\x1a\x19.engine.v1.RotationStatus\x12D\n" +
	"\x0fGetRotationPool\x12\x10.engine.v1.Empty\x1a\x1f.engine.v1.RotationPoolResponse\x12=\n" +
	"\x0eEnableRotation\x12\x19.engine.v1.RotationConfig\x1a\x10.engine.v1.Empty\x125\n" +
	"\x0fDisableRotation\x12\x10.engine.v1.Empty\x1a\x10.engine.v1.EmptyB\aZ\x05./;pbb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_engine_proto_goTypes = []any{
	(ProxyProtocol)(0),            // 0: engine.v1.ProxyProtocol
	(ProxyStatus)(0),              // 1: engine.v1.ProxyStatus
	(UpdateType)(0),               // 2: engine.v1.UpdateType
	(*Empty)(nil),                 // 3: engine.v1.Empty
	(*ProxyInfo)(nil),             // 4: engine.v1.ProxyInfo
	(*ConnectRequest)(nil),        // 5: engine.v1.ConnectRequest
	(*ConnectResponse)(nil),       // 6: engine.v1.ConnectResponse
	(*DisconnectRequest)(nil),     // 7: engine.v1.DisconnectRequest
	(*DisconnectResponse)(nil),    // 8: engine.v1.DisconnectResponse
	(*ProxyUpdate)(nil),           // 9: engine.v1.ProxyUpdate
	(*Region)(nil),                // 10: engine.v1.Region
	(*RegionsResponse)(nil),       // 11: engine.v1.RegionsResponse
	(*EngineStatus)(nil),          // 12: engine.v1.EngineStatus
	(*DiscoveryStatus)(nil),       // 13: engine.v1.DiscoveryStatus
	(*PoolSummary)(nil),           // 14: engine.v1.PoolSummary
	(*GetProxiesRequest)(nil),     // 15: engine.v1.GetProxiesRequest
	(*ProxiesResponse)(nil),       // 16: engine.v1.ProxiesResponse
	(*UsageReport)(nil),           // 17: engine.v1.UsageReport
	(*UsageResponse)(nil),         // 18: engine.v1.UsageResponse
	(*BlockStats)(nil),            // 19: engine.v1.BlockStats
	(*ToggleRequest)(nil),         // 20: engine.v1.ToggleRequest
	(*ToggleResponse)(nil),        // 21: engine.v1.ToggleResponse
	(*DomainCheckRequest)(nil),    // 22: engine.v1.DomainCheckRequest
	(*DomainCheckResponse)(nil),   // 23: engine.v1.DomainCheckResponse
	(*AuthRequest)(nil),           // 24: engine.v1.AuthRequest
	(*AuthResponse)(nil),          // 25: engine.v1.AuthResponse
	(*RefreshRequest)(nil),        // 26: engine.v1.RefreshRequest
	(*UserInfo)(nil),              // 27: engine.v1.UserInfo
	(*ConfigResponse)(nil),        // 28: engine.v1.ConfigResponse
	(*ConfigUpdateRequest)(nil),   // 29: engine.v1.ConfigUpdateRequest
	(*AnalyticsSummary)(nil),      // 30: engine.v1.AnalyticsSummary
	(*TopProxiesRequest)(nil),     // 31: engine.v1.TopProxiesRequest
	(*TopProxiesResponse)(nil),    // 32: engine.v1.TopProxiesResponse
	(*RotationStatus)(nil),        // 33: engine.v1.RotationStatus
	(*RotationPoolItem)(nil),      // 34: engine.v1.RotationPoolItem
	(*RotationPoolResponse)(nil),  // 35: engine.v1.RotationPoolResponse
	(*RotationConfig)(nil),        // 36: engine.v1.RotationConfig
	nil,                           // 37: engine.v1.BlockStats.CategoriesEnabledEntry
	nil,                           // 38: engine.v1.ConfigResponse.ConfigEntry
	nil,                           // 39: engine.v1.ConfigUpdateRequest.UpdatesEntry
	(*timestamppb.Timestamp)(nil), // 40: google.protobuf.Timestamp
}
var file_engine_proto_depIdxs = []int32{
	0,  // 0: engine.v1.ProxyInfo.protocol:type_name -> engine.v1.ProxyProtocol
	1,  // 1: engine.v1.ProxyInfo.status:type_name -> engine.v1.ProxyStatus
	40, // 2: engine.v1.ProxyInfo.last_checked:type_name -> google.protobuf.Timestamp
	4,  // 3: engine.v1.ConnectResponse.active_proxy:type_name -> engine.v1.ProxyInfo
	40, // 4: engine.v1.ConnectResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 5: engine.v1.ProxyUpdate.type:type_name -> engine.v1.UpdateType
	4,  // 6: engine.v1.ProxyUpdate.proxy:type_name -> engine.v1.ProxyInfo
	14, // 7: engine.v1.ProxyUpdate.pool:type_name -> engine.v1.PoolSummary
	40, // 8: engine.v1.ProxyUpdate.timestamp:type_name -> google.protobuf.Timestamp
	10, // 9: engine.v1.RegionsResponse.regions:type_name -> engine.v1.Region
	4,  // 10: engine.v1.EngineStatus.active_proxy:type_name -> engine.v1.ProxyInfo
	14, // 11: engine.v1.EngineStatus.pool:type_name -> engine.v1.PoolSummary
	13, // 12: engine.v1.EngineStatus.discovery:type_name -> engine.v1.DiscoveryStatus
	4,  // 13: engine.v1.ProxiesResponse.proxies:type_name -> engine.v1.ProxyInfo
	37, // 14: engine.v1.BlockStats.categories_enabled:type_name -> engine.v1.BlockStats.CategoriesEnabledEntry
	27, // 15: engine.v1.AuthResponse.user:type_name -> engine.v1.UserInfo
	38, // 16: engine.v1.ConfigResponse.config:type_name -> engine.v1.ConfigResponse.ConfigEntry
	39, // 17: engine.v1.ConfigUpdateRequest.updates:type_name -> engine.v1.ConfigUpdateRequest.UpdatesEntry
	4,  // 18: engine.v1.AnalyticsSummary.best_proxy:type_name -> engine.v1.ProxyInfo
	4,  // 19: engine.v1.AnalyticsSummary.worst_proxy:type_name -> engine.v1.ProxyInfo
	4,  // 20: engine.v1.TopProxiesResponse.proxies:type_name -> engine.v1.ProxyInfo
	34, // 21: engine.v1.RotationPoolResponse.proxies:type_name -> engine.v1.RotationPoolItem
	5,  // 22: engine.v1.ProxyEngine.Connect:input_type -> engine.v1.ConnectRequest
	7,  // 23: engine.v1.ProxyEngine.Disconnect:input_type -> engine.v1.DisconnectRequest
	3,  // 24: engine.v1.ProxyEngine.GetActiveProxy:input_type -> engine.v1.Empty
	3,  // 25: engine.v1.ProxyEngine.StreamProxyUpdates:input_type -> engine.v1.Empty
	3,  // 26: engine.v1.ProxyEngine.GetRegions:input_type -> engine.v1.Empty
	3,  // 27: engine.v1.ProxyEngine.GetEngineStatus:input_type -> engine.v1.Empty
	3,  // 28: engine.v1.ProxyEngine.GetPoolSummary:input_type -> engine.v1.Empty
	15, // 29: engine.v1.ProxyEngine.GetProxies:input_type -> engine.v1.GetProxiesRequest
	17, // 30: engine.v1.ProxyEngine.ReportUsage:input_type -> engine.v1.UsageReport
	3,  // 31: engine.v1.ProxyEngine.GetBlockStats:input_type -> engine.v1.Empty
	20, // 32: engine.v1.ProxyEngine.ToggleAdBlock:input_type -> engine.v1.ToggleRequest
	22, // 33: engine.v1.ProxyEngine.CheckDomain:input_type -> engine.v1.DomainCheckRequest
	24, // 34: engine.v1.ProxyEngine.Authenticate:input_type -> engine.v1.AuthRequest
	26, // 35: engine.v1.ProxyEngine.RefreshToken:input_type -> engine.v1.RefreshRequest
	3,  // 36: engine.v1.ProxyEngine.GetConfig:input_type -> engine.v1.Empty
	29, // 37: engine.v1.ProxyEngine.UpdateConfig:input_type -> engine.v1.ConfigUpdateRequest
	3,  // 38: engine.v1.ProxyEngine.GetAnalyticsSummary:input_type -> engine.v1.Empty
	31, // 39: engine.v1.ProxyEngine.GetTopProxies:input_type -> engine.v1.TopProxiesRequest
	3,  // 40: engine.v1.ProxyEngine.GetRotationStatus:input_type -> engine.v1.Empty
	3,  // 41: engine.v1.ProxyEngine.GetRotationPool:input_type -> engine.v1.Empty
	36, // 42: engine.v1.ProxyEngine.EnableRotation:input_type -> engine.v1.RotationConfig
	3,  // 43: engine.v1.ProxyEngine.DisableRotation:input_type -> engine.v1.Empty
	6,  // 44: engine.v1.ProxyEngine.Connect:output_type -> engine.v1.ConnectResponse
	8,  // 45: engine.v1.ProxyEngine.Disconnect:output_type -> engine.v1.DisconnectResponse
	4,  // 46: engine.v1.ProxyEngine.GetActiveProxy:output_type -> engine.v1.ProxyInfo
	9,  // 47: engine.v1.ProxyEngine.StreamProxyUpdates:output_type -> engine.v1.ProxyUpdate
	11, // 48: engine.v1.ProxyEngine.GetRegions:output_type -> engine.v1.RegionsResponse
	12, // 49: engine.v1.ProxyEngine.GetEngineStatus:output_type -> engine.v1.EngineStatus
	14, // 50: engine.v1.ProxyEngine.GetPoolSummary:output_type -> engine.v1.PoolSummary
	16, // 51: engine.v1.ProxyEngine.GetProxies:output_type -> engine.v1.ProxiesResponse
	18, // 52: engine.v1.ProxyEngine.ReportUsage:output_type -> engine.v1.UsageResponse
	19, // 53: engine.v1.ProxyEngine.GetBlockStats:output_type -> engine.v1.BlockStats
	21, // 54: engine.v1.ProxyEngine.ToggleAdBlock:output_type -> engine.v1.ToggleResponse
	23, // 55: engine.v1.ProxyEngine.CheckDomain:output_type -> engine.v1.DomainCheckResponse
	25, // 56: engine.v1.ProxyEngine.Authenticate:output_type -> engine.v1.AuthResponse
	25, // 57: engine.v1.ProxyEngine.RefreshToken:output_type -> engine.v1.AuthResponse
	28, // 58: engine.v1.ProxyEngine.GetConfig:output_type -> engine.v1.ConfigResponse
	28, // 59: engine.v1.ProxyEngine.UpdateConfig:output_type -> engine.v1.ConfigResponse
	30, // 60: engine.v1.ProxyEngine.GetAnalyticsSummary:output_type -> engine.v1.AnalyticsSummary
	32, // 61: engine.v1.ProxyEngine.GetTopProxies:output_type -> engine.v1.TopProxiesResponse
	33, // 62: engine.v1.ProxyEngine.GetRotationStatus:output_type -> engine.v1.RotationStatus
	35, // 63: engine.v1.ProxyEngine.GetRotationPool:output_type -> engine.v1.RotationPoolResponse
	3,  // 64: engine.v1.ProxyEngine.EnableRotation:output_type -> engine.v1.Empty
	3,  // 65: engine.v1.ProxyEngine.DisableRotation:output_type -> engine.v1.Empty
	44, // [44:66] is the sub-list for method output_type
	22, // [22:44] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		EnumInfos:         file_engine_proto_enumTypes,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
